config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup',     to: 'users#new'
  get 'login',      to: 'sessions#new'
  post 'login',     to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
  
  scope :by_admin, -> { joins(:user).where('users.is_admin' => 'true') }

  def owned_by?(user_to_verify)
    user == user_to_verify
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password

  has_many :articles
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorised
  helper_method :current_user
  helper_method :logged_in?
  helper_method :logged_in_as_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    current_user.present?
  end

  def logged_in_as_admin?
    current_user.present? && current_user.is_admin
  end
  
  def authorised
    redirect_to login_path unless logged_in?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authorised, only: [:index, :show]

  before_action :set_article, except: [:index, :new, :create]
  before_action :authorised_for_article_actions, except: [:index, :new, :create, :show]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
     flash[:success] = "Article was updated"
     redirect_to article_path(@article)
    else
     flash[:success] = "Article was not updated"
     render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "Article was deleted"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def authorised_for_article_actions
    unless @article.owned_by?(current_user) || logged_in_as_admin?
      flash[:danger] = "You are not authorised to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authorised, only: [:index]

	def index
    @articles = Article.by_admin.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
	end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController

  skip_before_action :authorised, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      if @user.is_admin
        flash[:danger] = "You have logged in as a site admin, use with care"
      else
        flash[:success] = "You have logged in"
      end
      redirect_to articles_path
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
   end

   def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
   end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorised, only: [:index, :new, :create, :show]

  before_action :authorised_for_user_actions, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the my test blog, #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
     end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    flash[:success] = "User was deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def authorised_for_user_actions
    unless current_user = User.find(params[:id])
      flash[:danger] = "You are not authorised to perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
end
end

app/views/articles/_form.html.erb
<%= render partial: 'shared/errors', locals: { obj: @article } %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-6">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-success btn-large' %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h1>Edit Article</h1>
</div>

<%= render partial: 'form' %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <%= link_to 'Back', articles_path, class: "btn btn-primary btn-large" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-danger btn-large" %>
  </div>
</div>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<div align="center">
  <%= will_paginate @articles %>
</div>

<%= render partial: 'shared/article', locals: { obj: @articles } %>

<div align="center">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Create an article</h1>
    </div>
    
    <%= render partial: 'form' %>

    <div class="col-xs-8 col-xs-offset-2">
        <%= link_to 'Back', articles_path, :class => "btn btn-primary btn-large" %>
    </div>        
</div>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <%= render partial: 'shared/controls', locals: { article: @article } %>
</div>

<div class="clearfix"></div>
<div class="col-xs-8 col-xs-offset-2">
  <%= link_to 'Back', articles_path, :class => "btn btn-xs btn-success" %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Jamie Lafferty", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Blog", root_url(:subdomain=>'blog') %></li>
      </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_blog.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ruby on Rails", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Create Article", new_article_path %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in",  login_path %></li>
          <li><%= link_to "Jamie Lafferty Home", root_url(:subdomain=>false) %></li>
        <% end %>  
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <li><%= link_to "My profile", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Jamie Lafferty Home", root_url(:subdomain=>false) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation_blog' %>
    <%= render partial: 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="col-xs-8 col-xs-offset-2">
    <h1>Jamie Lafferty</h1>
    <p>I am an ambitious, highly-skilled software development professional with more than 8 years experience in software design, development and integration. My roles have enabled me to expand my skills in web systems development, real-time application development and maintenance, integrating with high-profile payment systems, embedded software development, application programming and now Ruby on Rails.</p>
    <p>I have created this site in order to learn Ruby on Rails in my spare time, as this is something I have been extremely interested in learning.</p>
    <p>This project has full CI/CD using Heroku & Codeship.</p>
    <p>Below is a living TIL (Today I Learned) history of my journey into the world of Ruby.</p>
</div>

<%= render partial: 'shared/article', locals: { obj: @articles } %>

<div align="center">
  <%= will_paginate @articles %>
</div>

app/views/pages/ruby_index.html.erb
<div class="col-xs-8 col-xs-offset-2">
    <h1>Welcome to Blog</h1>
</div>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.description, length: 100) %>
        <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
      <%= render partial: 'shared/controls', locals: { article: article } %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_controls.html.erb
<% if article.owned_by?(current_user) || logged_in_as_admin? %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg|%>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
</div>

app/views/users/_controls.html.erb
<% if user == current_user %>
  <div class="user-actions">
    <%= link_to "Edit", edit_user_path(user), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete your profile? Once it's gone, it's gone..."}, class: "btn btn-xs btn-danger" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render partial: 'shared/errors', locals: { obj: @user } %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :email %>
            </div>
            <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password %>
            </div>
            <div class="col-sm-8">
                <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
                <%= link_to 'Cancel', user_path(current_user), :class => "btn btn-cancel btn-danger" %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Edit User Account</h1>
    </div>
    <%= render partial: 'form' %>
</div>

app/views/users/index.html.erb
<div align="center">
    <h1 align="center">All Users</h1>
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="article-title">
                        <% if user.is_admin %>
                            <i title="User is an admin" class="fas fa-user-secret"></i>
                        <% end %>
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                    
                </div>
            </div>
        </ul>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Signup</h1>
    </div>
    <%= render partial: 'form' %>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>
            <%= gravatar_for @user, size: 50 %>
            Welcome to <%= @user.username %>'s page
            <% if @user.is_admin %>
                <i title="User is an admin" class="fas fa-user-secret"></i>
            <% end %>
        </h1>
    </div>
    <div class="col-xs-8 col-xs-offset-2">
        <%= render partial: 'controls', locals: { user: @user } %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>

<div align="center">
    <%= will_paginate @user_articles %>
</div>

<%= render partial: 'shared/article', locals: { obj: @user.articles } %>

<div align="center">
    <%= will_paginate @user_articles %>
</div>